no wraps for try excet statement
gregoil/ipdbugger pull request #15
Opened 2019-01-20 10:04 UTC by yakobu

2019-01-21 11:50 UTC, UnDarkle commented on ipdbugger/__init__.py
> -            # Delete the debugger decorator of the function
we needed it (for some reason)

2019-01-21 11:52 UTC, UnDarkle commented on ipdbugger/__init__.py
> +    if sys.version_info > (3, 0):  # pragma: no cover
make sure we also wrap the try-except statement itself with ipdbugger

2019-01-21 11:52 UTC, UnDarkle requested changes
2 comments

2019-01-27 09:00 UTC, osherdp requested changes

2019-01-27 09:00 UTC, osherdp commented on ipdbugger/__init__.py
> +        for except_handler in excepted + self.exception_handlers:
use concat* from itertools

2019-01-27 09:00 UTC, osherdp commented on ipdbugger/__init__.py
> +                handlers=self.exception_handlers[:],
check if you still need to clone, since you're creating a new list inside

2019-01-27 09:00 UTC, osherdp commented on ipdbugger/__init__.py
> +            is_python_3 = sys.version_info > (3, 0)
elkis, whady'a think?

2019-01-27 09:00 UTC, osherdp commented on setup.py
> +__version__ = "2.1.3"
2.1.0

2019-01-27 09:00 UTC, osherdp commented on tests/test_debug.py
> +def test_wrapping_try_except_statement_with_no_specific_exception_type():
test_wrapping_general_try_except, or unbound catch

2019-01-27 18:07 UTC, yakobu commented on ipdbugger/__init__.py
> -            # Delete the debugger decorator of the function
K

2019-01-27 18:09 UTC, yakobu commented on ipdbugger/__init__.py
> +        for except_handler in excepted + self.exception_handlers:
K

2019-01-29 08:23 UTC, merged